import { StyleSheet } from "react-native";
import { COLOR, FONT } from "../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLOR.background,
    padding: 16,
  },
  header: {
    marginTop: 20,
    marginBottom: 20,
  },
  headerText: {
    fontFamily: FONT.bold,
    fontSize: 26,
    color: COLOR.primary,
    textAlign: "center",
  },
  subHeaderText: {
    fontFamily: FONT.regular,
    fontSize: 16,
    color: COLOR.primary,
    textAlign: "center",
    marginTop: 5,
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: COLOR.lightBackground,
    borderRadius: 30,
    marginBottom: 20,
    height: 50,
  },
  tab: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
  },
  activeTab: {
    backgroundColor: COLOR.primary,
  },
  tabText: {
    fontFamily: FONT.regular,
    fontSize: 14,
    color: COLOR.primary,
  },
  activeTabText: {
    color: COLOR.white,
    fontFamily: FONT.bold,
  },
  createButton: {
    backgroundColor: COLOR.primary,
    marginTop: 10,
    width: "90%",
    alignSelf: "center",
  },
  noChallengesContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  noChallengesText: {
    fontFamily: FONT.regular,
    fontSize: 18,
    color: COLOR.primary,
    textAlign: "center",
    marginTop: 10,
  },
  challengeCard: {
    backgroundColor: COLOR.lightBackground,
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  challengeTitle: {
    fontFamily: FONT.bold,
    fontSize: 18,
    color: COLOR.primary,
    marginBottom: 5,
  },
  challengeType: {
    fontFamily: FONT.italic,
    fontSize: 14,
    color: COLOR.subPrimary,
    marginBottom: 8,
  },
  challengeInfo: {
    fontFamily: FONT.regular,
    fontSize: 14,
    color: COLOR.primary,
    marginBottom: 5,
  },
  challengeMetrics: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  metricContainer: {
    alignItems: "center",
  },
  metricValue: {
    fontFamily: FONT.bold,
    fontSize: 18,
    color: COLOR.primary,
  },
  metricLabel: {
    fontFamily: FONT.regular,
    fontSize: 12,
    color: COLOR.subPrimary,
  },
  statusBadge: {
    position: "absolute",
    top: 15,
    right: 15,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
  },
  statusText: {
    fontFamily: FONT.bold,
    fontSize: 12,
    color: COLOR.white,
  },
  joinButton: {
    backgroundColor: COLOR.darkblue,
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    alignSelf: "flex-end",
    marginTop: 10,
  },
  joinButtonText: {
    fontFamily: FONT.bold,
    fontSize: 14,
    color: COLOR.white,
  },
  viewDetailsButton: {
    backgroundColor: COLOR.primary,
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    alignSelf: "flex-end",
    marginTop: 10,
  },
  viewDetailsButtonText: {
    fontFamily: FONT.bold,
    fontSize: 14,
    color: COLOR.white,
  },
  formContainer: {
    backgroundColor: COLOR.lightBackground,
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
  },
  inputLabel: {
    fontFamily: FONT.bold,
    fontSize: 16,
    color: COLOR.primary,
    marginBottom: 8,
  },
  timeFrameOption: {
    backgroundColor: COLOR.white,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "transparent",
  },
  selectedTimeFrame: {
    borderColor: COLOR.primary,
  },
  timeFrameText: {
    fontFamily: FONT.regular,
    fontSize: 16,
    color: COLOR.primary,
  },
  ruleTypeContainer: {
    backgroundColor: COLOR.white,
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: "transparent",
  },
  selectedRuleType: {
    borderColor: COLOR.primary,
  },
  ruleTypeTitle: {
    fontFamily: FONT.bold,
    fontSize: 18,
    color: COLOR.primary,
    marginBottom: 5,
  },
  ruleTypeDescription: {
    fontFamily: FONT.regular,
    fontSize: 14,
    color: COLOR.subPrimary,
  },
  navigationButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  backButton: {
    backgroundColor: COLOR.lightblue,
    width: "45%",
  },
  nextButton: {
    backgroundColor: COLOR.primary,
    width: "45%",
  },
  summarySection: {
    marginBottom: 20,
  },
  summaryLabel: {
    fontFamily: FONT.bold,
    fontSize: 16,
    color: COLOR.primary,
    marginBottom: 5,
  },
  summaryValue: {
    fontFamily: FONT.regular,
    fontSize: 18,
    color: COLOR.subPrimary,
    marginBottom: 10,
  },
  inviteButton: {
    backgroundColor: COLOR.lightblue,
    width: "100%",
    marginBottom: 15,
  },
  leaderboard: {
    marginTop: 20,
  },
  leaderboardTitle: {
    fontFamily: FONT.bold,
    fontSize: 20,
    color: COLOR.primary,
    marginBottom: 15,
  },
  participantCard: {
    flexDirection: "row",
    backgroundColor: COLOR.white,
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    alignItems: "center",
  },
  rankNumber: {
    fontFamily: FONT.bold,
    fontSize: 18,
    color: COLOR.primary,
    width: 40,
    textAlign: "center",
  },
  userInfo: {
    flex: 1,
    marginLeft: 10,
  },
  userName: {
    fontFamily: FONT.bold,
    fontSize: 16,
    color: COLOR.primary,
  },
  userStats: {
    fontFamily: FONT.regular,
    fontSize: 14,
    color: COLOR.subPrimary,
  },
  score: {
    fontFamily: FONT.bold,
    fontSize: 18,
    color: COLOR.primary,
    marginRight: 5,
  },
  congratsContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  congratsText: {
    fontFamily: FONT.bold,
    fontSize: 24,
    color: COLOR.primary,
    textAlign: "center",
  },
  winnerName: {
    fontFamily: FONT.bold,
    fontSize: 28,
    color: COLOR.green,
    marginVertical: 10,
    textAlign: "center",
  },
  statContainer: {
    backgroundColor: COLOR.lightBackground,
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    width: "100%",
  },
  statTitle: {
    fontFamily: FONT.bold,
    fontSize: 16,
    color: COLOR.primary,
    marginBottom: 5,
  },
  statValue: {
    fontFamily: FONT.regular,
    fontSize: 18,
    color: COLOR.subPrimary,
  },
});
